spring:
  application:
    name: coupon-server-eureka

server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    # 是否从 Eureka Server 中获取注册信息，如果是单节点的 Eureka Server 不需要同步其他结点的数据
    fetch-registry: false
    # 是否将自己注册到 Eureka Server，由于当前应用是单节点的 Eureka Server，需要设为 false
    register-with-eureka: false
    # 用于设置 Eureka Server 所在地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
