server:
  port: 7001
  servlet:
    # 微服务路径前缀
    context-path: /coupon/template
spring:
  application:
    name: coupon-service-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # 格式化SQL
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_server_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Hxl.123+!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CouponServerHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    com.hxl.coupon: debug